/**
 * WARNING!
 * Do NOT edit this file as it is automatically generated
 * run "yarn generate:icons" to update
 */

  
import type { IconLibProps } from "@/libs/icons/icons.types";

const IconSpeaker = ({ height = 24, width = 24 }: IconLibProps) => (
<svg
  xmlns="http://www.w3.org/2000/svg"
  width={width}
  height={height}
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  strokeWidth="2"
  strokeLinecap="round"
  strokeLinejoin="round"
>
  <rect x="4" y="2" width="16" height="20" rx="2" ry="2" />
  <circle cx="12" cy="14" r="4" />
  <line x1="12" y1="6" x2="12.01" y2="6" />
</svg>
);
  
export default IconSpeaker;